# Generated by Django 4.2.8 on 2024-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_prdts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='save_trm',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='save_trm',
            field=models.IntegerField(max_length=3),
        ),
    ]
