# Generated by Django 4.2.8 on 2024-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_prdts', '0002_alter_depositoptions_save_trm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='save_trm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='save_trm',
            field=models.IntegerField(),
        ),
    ]
